# Generated by Django 4.2.16 on 2024-11-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.CharField(max_length=100, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость позиции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано : ')),
            ],
        ),
    ]
