# Generated by Django 5.1.3 on 2024-11-24 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_feedback_alter_product_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='email',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='message',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
